import type { NextPage } from 'next'
import Head from 'next/head'
import { dehydrate, QueryClient, useQuery } from '@tanstack/react-query'
import styles from '../styles/Home.module.css'

const getPosts = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts')
  const posts = await response.json()
  return posts
}

const Home: NextPage = () => {
  const { data } = useQuery(['posts'], getPosts)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data && JSON.stringify(data)}
      </main>

    </div>
  )
}

export async function getStaticProps() {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery(['posts'], getPosts)

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

export default Home
