import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext } from 'react'
import { dehydrate, QueryClient, useQuery } from '@tanstack/react-query'
import Web3 from 'web3'
import { Web3Context } from '../api/Web3Provider'
import { Button } from '@mantine/core';

const Home: NextPage = () => {
  const web3 = useContext(Web3Context)
  const { data: lastBlockNumber } = useQuery(['lastBlockNumber'], () => web3.eth.getBlockNumber())
  const { data: lastBlock } = useQuery(['lastBlock'], () => web3.eth.getBlock(lastBlockNumber as number), {
    enabled: !!lastBlockNumber
  })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button>
          Settings
        </Button>
        <pre>
          {lastBlock && JSON.stringify(lastBlock, null, 2)}
        </pre>
      </main>

    </div>
  )
}

export default Home
