import type { NextPage } from 'next'
import Head from 'next/head'
import { BlocksTable } from '../components/BlocksTable' 

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <pre>
          <BlocksTable/>
        </pre>
      </main>

    </div>
  )
}

export default Home
